### ISSUE TITLE
Use Makie's plot recipes; avoid type piracy

### ISSUE THREAD

**Issue by navidcy** [navidcy/Imaginocean.jl#1]
Here we might be committing a type piracy:

https://github.com/navidcy/Imaginocean.jl/blob/b1089c42de2c2517ec17d7905cbae4f9e7a8cad9/src/Imaginocean.jl#L213

Seems like proper way forward would be to use Makie's [plot recipes functionality](https://docs.makie.org/stable/documentation/recipes/).

cc @glwagner

**Comment by jbisits** [comment]
Sorry to jump in on this, just saw the package and though it looked cool and useful! Apologies if you have already considered the following. For `heatmap!` might also be able to use `convert_arguments` from Makie.jl for the type `Field` (it saves writing a whole plotting recipe). It would look something like

```julia
function Makie.convert_arguments(P::SurfaceLike, field::Field)

    # collect longitude, latitude and the variable for plotting
    return convert_arguments(P, lon, lat, plot_var)

end
```

after which you can just use `heatmap!(ax, field)`. I used something similar [here](https://jbisits.github.io/OceanRasterConversions.jl/dev/literated/ECCO_example/#Plotting-with-[GeoMakie.jl](https://github.com/MakieOrg/GeoMakie.jl)) and was actually trying to do something for a `model.field` but ran into some issues so could have a crack at this when I get a chance if you like?

**Comment by navidcy** [comment]
This package is really in primitive stages atm. Thanks for the suggestion! What is `P::SurfaceLike` above?

**Comment by navidcy** [comment]
Feel free to have a crack!

**Comment by jbisits** [comment]
>What is P::SurfaceLike above?

It is the `PlotType`. `SurfaceLike` includes plots of `heatmap`s, `contour`s so may not be right thing to be used here.
